config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
    sessions: 'admin/sessions'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'serch' => 'serches#serch'
  scope module: :public do
    devise_for :users, controllers: {
      sessions: 'public/sessions',
      passwords: 'public/passwords',
      registrations: 'public/registrations'
    }

    root to: 'homes#top'
    get 'about' => 'homes#about'
    get 'my_page' => 'users#my_page'
    get 'users/confirm' => 'users#confirm'
    patch 'users/withdraw' => 'users#withdraw'
    get 'favorites' => 'users#favorites'
    get '/search/genres/:id' => 'searches#genre', as: 'genre_search'
    get 'search' => 'searches#search'
    resources :users, only: %i[edit update index show] do
      resource :relationships, only: %i[create destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
    end
    resources :posts, only: %i[new create index show destroy] do
      resource :favorites, only: %i[create destroy]
      get 'favorites/index' => 'users/index'
      resources :post_comments, only: %i[create destroy]
    end
    resources :notifications, only: :index
    resources :chats, only: [:show, :create]
  end

  namespace :admin do
    resources :users, only: %i[edit update index show destroy]
    resources :genres, only: %i[create edit update index destroy]
  end
end

app/views/layouts/_error_message.html.erb
<div class="error_message">
  <% if hoge.errors.any? %>
    <%= hoge.errors.count %>件のエラーが発生しました<br>
    <% hoge.errors.full_messages.each do |message| %>
      <%= message %><br>
    <% end %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <title>Parenting</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!--link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/3.18.1/build/cssreset/cssreset-min.css"-->

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- drawer.css -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/drawer/3.2.2/css/drawer.min.css">
    <!-- jquery &amp; iScroll -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/iScroll/5.2.0/iscroll.min.js"></script>
    <!-- drawer.js -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/drawer/3.2.2/js/drawer.min.js"></script>

    <!--<link href="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.7.1/css/lightbox.css" rel="stylesheet">-->
    <!--<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>-->
    <!--<script src="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.7.1/js/lightbox.min.js" type="text/javascript"></script>-->

  </head>

  <body class="drawer drawer--right">
    <div class="side">
      <div class="side_in">
        <header class="header">
          <div class="header_logo">
            <%= link_to root_path, data: {"turbolinks" => false}, class: 'navbar-brand  ml-3 col-md-3 offset-md-1' do %>
              <%= image_tag 'logo.jpg', :size => '100x100', class: 'd-inline-block'%>
            <% end %>
          </div>
          <% unless admin_signed_in? %>
            <div class="search">
              <%= form_with url: search_path, local: true, method: :get do |f| %>
              <div class="search_form">
                <%= f.text_field :word, placeholder: "検索ワード", class: "form-control" %>
              </div>
              <div class="search_btn">
                <button type="submit" class="form-control btn btn-outline-light">
                  <i class="fas fa-search"></i>
                </button>
              </div>
              <% end %>
            </div>
          <% end %>

          <!--パソコンサイズにした時には、サイドバーを使用-->
          <div class="display-block">
            <div class="nav">
              <ul class="navbar-nav mr-auto">
                <% if user_signed_in? %>
                  <li><%= link_to "通知", notifications_path, class: 'text-decoration-none text-light fas fa-bell' %></li>
                  <li><%= link_to "サイト概要", about_path, class: 'text-decoration-none text-light fas fa-exclamation-circle' %></li>
                  <li><%= link_to "マイページ", my_page_path, class: 'text-decoration-none text-light fas fa-user' %></li>
                  <li><%= link_to "ユーザー一覧", users_path, class: 'text-decoration-none text-light fas fa-users' %></li>
                  <li><%= link_to "新規投稿", new_post_path, class: 'text-decoration-none text-light fas fa-pen' %></li>
                  <li><%= link_to "投稿一覧", posts_path, class: 'text-decoration-none text-light fas fa-list' %></li>
                  <li><%= link_to "ログアウト", destroy_user_session_path, class: 'text-decoration-none text-light fas fa-sign-out-alt', method: :delete %></li>
                <% elsif admin_signed_in? %>
                  <li><%= link_to "ユーザー一覧", admin_users_path, class: 'text-decoration-none text-dark' %></li>
                  <li><%= link_to "ジャンル一覧", admin_genres_path, class: 'text-decoration-none text-dark' %></li>
                  <li><%= link_to "ログアウト", destroy_admin_session_path, class: 'text-decoration-none text-dark', method: :delete %></li>
                <% else %>
                  <li><%= link_to "サイト概要", about_path, class: 'text-decoration-none text-light fas fa-exclamation-circle' %></li>
                  <li><%= link_to "ユーザー一覧", users_path, class: 'text-decoration-none text-light fas fa-users' %></li>
                  <li><%= link_to "投稿一覧", posts_path, class: 'text-decoration-none text-light fas fa-list' %></li>
                  <li><%= link_to "新規登録", new_user_registration_path, class: 'text-decoration-none text-light fas fa-user-plus' %></li>
                  <li><%= link_to "ログイン", new_user_session_path, class: 'text-decoration-none text-light fas fa-sign-in-alt' %></li>
                <% end %>
                </ul>
              </div>
            </div>
          <!--スマートフォンサイズにした時には、ドロワーメニューを使用-->
          <button type="button" class="drawer-toggle drawer-hamburger display-none">
            <span class="sr-only">toggle navigation</span>
            <span class="drawer-hamburger-icon"></span>
          </button>
          <nav class="drawer-nav" role="navigation">
            <div class="nav">
            <ul class="drawer-menu">
              <% if user_signed_in? %>
                <li><%= link_to "通知", notifications_path, class: 'text-decoration-none text-dark fas fa-bell' %></li>
                <li><%= link_to "サイト概要", about_path, class: 'text-decoration-none text-dark fas fa-exclamation-circle' %></li>
                <li><%= link_to "マイページ", my_page_path, class: 'text-decoration-none text-dark fas fa-user' %></li>
                <li><%= link_to "ユーザー一覧", users_path, class: 'text-decoration-none text-dark fas fa-users' %></li>
                <li><%= link_to "新規投稿", new_post_path, class: 'text-decoration-none text-dark fas fa-pen' %></li>
                <li><%= link_to "投稿一覧", posts_path, class: 'text-decoration-none text-dark fas fa-list' %></li>
                <li><%= link_to "ログアウト", destroy_user_session_path, class: 'text-decoration-none text-dark fas fa-sign-out-alt', method: :delete %></li>
              <% elsif admin_signed_in? %>
                <li><%= link_to "ログアウト", destroy_admin_session_path, class: 'text-decoration-none text-dark', method: :delete %></li>
                <li><%= link_to "ユーザー一覧", admin_users_path, class: 'text-decoration-none text-dark' %></li>
                <li><%= link_to "ジャンル一覧", admin_genres_path, class: 'text-decoration-none text-dark' %></li>
              <% else %>
                <li><%= link_to "サイト概要", about_path, class: 'text-decoration-none text-dark fas fa-exclamation-circle' %></li>
                <li><%= link_to "ユーザー一覧", users_path, class: 'text-decoration-none text-dark fas fa-users' %></li>
                <li><%= link_to "投稿一覧", posts_path, class: 'text-decoration-none text-dark fas fa-list' %></li>
                <li><%= link_to "新規登録", new_user_registration_path, class: 'text-decoration-none text-dark fas fa-user-plus' %></li>
                <li><%= link_to "ログイン", new_user_session_path, class: 'text-decoration-none text-dark fas fa-sign-in-alt' %></li>
              <% end %>
            </ul>
            </div>
          </nav>
        </header>
        <div class="yield">
          <%= yield %>
          <span id="back">
            <a href="#">
              <%= image_tag asset_path('arrow.png'), data: {"turbolinks" => false}, class: "arrow" %>
            </a>
          </span>
        </div>
      </div>
    </div>
  </body>
</html>